site_name: Modul DAT_SKI
repo_url: https://github.com/ABBTS-DAT-SKI/wissensdatenbank
site_url: https://abbts-dat-ski.github.io/wissensdatenbank/
site_description: Wissensdatenbank für das Modul DAT-SKI
edit_uri: edit/wissensdatenbank/docs/
repo_name: ABBTS-DAT-SKI/wissensdatenbank

nav:
  - Startseite: index.md
  - Mini Challenge: mini_challenge.md
  - Python Installation: python_installation.md
  - Wissensdatenbank: 
      - Datenverarbeitung: 
          - Einführung Pandas: data-engineering/introduction.md
          - Übersicht Datentypen: data-engineering/data_types.md
          - Datenformate: data-engineering/data_formats.md
          - Spaltenmanipulationen: data-engineering/column_manipulations.md
          - Entfernen von Duplikaten: data-engineering/drop_duplicates.md
          - Befüllen von fehlenden Werten: data-engineering/fillna.md
          - Entfernen von Ausreissern: data-engineering/outliers.md
          - Time-Indexes: data-engineering/time_indexes.md
          - Resampling: data-engineering/resampling.md
          - Imputationen: data-engineering/imputation.md
          - Horizontale Joins: data-engineering/joins.md
          - Pivot/Melt: data-engineering/pivot_melt.md
      - Statistik: 
          - Univariate Statistik: statistics/univariate_statistics.md

plugins:
  - search

theme:
  name: material
  feature:
    tabs: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    logo: fontawesome/solid/flask
    repo: fontawesome/brands/github

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - github-callouts

extra_javascript:
  - javascripts/katex.js
  - javascripts/auto-render.min.js
  - javascripts/katex.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/katex.min.css
